### ISSUE TITLE
No way to sync/autosync tracks

### ISSUE THREAD

**Issue by caesarsol** [scriptify/soundcycle#1]
Hi,
I always wanted to create something like this!
Since you arrived first, I would be happy to help :)

Don't you think a cool addition could be to automatically sync tracks so they can loop seamessly?

I think with a bit of manipulation it could be possible, or at least with a truncation of the recording based on the first track or a multiple of it (the first track will supposedly be something with a base rhythm?)

Also, I twiddled a bit with sound visualization (http://sequencer.surge.sh/) and I would like to add some to the track! I am thinking about making it in a WebGL shader for maximum performance.

Let me know what you think!

**Comment by caesarsol** [comment]
Just noticed you are using React + MobX, even more convinced now!

(Suggestion: take a look at `mobx-state-tree` which builds on `mobx` and elaborates the same concept in a super cool way)

**Comment by scriptify** [comment]
Hello Caesar,
nice to hear that! There's a lot to do, it will never get boring.
The underlying library which is responsible for looping already does something similar. It is part of [sountility](https://github.com/scriptify/sountility), a collection of libraries which are internally used by Soundcycle. It's called [audiolooper](https://github.com/scriptify/sountility/blob/master/packages/audiolooper/README.md). If you have a look at the [README](https://github.com/scriptify/sountility/blob/master/packages/audiolooper/README.md), the way how it tries to sync the incoming tracks is described in more detail. Tell me what you think!

I am sure that WebGL would be the best way to add some high performance audio visualizations, everything else can become very resource hungry, at least what I experienced (I tried to add some visualizations before, but the impact on the UI performance was just too big).

Yes, `mobx-state-tree` is nice indeed. I would really like to re-implement many aspects of the application to improve the overall design and structure. State handling would be a good starting point.
It would be nice if you could help!
